# Generated by Django 4.2.9 on 2024-04-23 13:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('customer_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_city', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_dist', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_plan', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_status', models.IntegerField(default=0)),
                ('username', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(related_name='customer_groups', to='auth.group')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_by', models.CharField(max_length=100)),
                ('package_name', models.CharField(max_length=30)),
                ('package_price', models.CharField(max_length=30)),
                ('package_days', models.IntegerField()),
                ('package_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_by', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('varient', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('mrpprice', models.IntegerField()),
                ('saleprice', models.IntegerField()),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPackageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shriharidoodhapp.package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shriharidoodhapp.products')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='products',
            field=models.ManyToManyField(to='shriharidoodhapp.products'),
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('approved_status', models.IntegerField(default=0)),
                ('delievery_address', models.CharField(max_length=100)),
                ('order_qty', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shriharidoodhapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='daily_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('approved_status', models.IntegerField(default=0)),
                ('delievery_address', models.CharField(max_length=100)),
                ('customer_plan', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shriharidoodhapp.package')),
            ],
        ),
        migrations.AddField(
            model_name='customer_list',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shriharidoodhapp.package'),
        ),
        migrations.AddField(
            model_name='customer_list',
            name='user_permissions',
            field=models.ManyToManyField(related_name='customer_user_permissions', to='auth.permission'),
        ),
    ]
