# Generated by Django 4.2.9 on 2024-04-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shriharidoodhapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_orders',
            name='customer_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='daily_orders',
            name='delievery_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
