# Generated by Django 4.2.9 on 2024-05-02 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shriharidoodhapp', '0002_alter_daily_orders_customer_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_list',
            name='daily_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shriharidoodhapp.daily_orders'),
        ),
        migrations.AddField(
            model_name='customer_list',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shriharidoodhapp.orders'),
        ),
    ]
