# Generated by Django 4.2.9 on 2024-05-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shriharidoodhapp', '0003_customer_list_daily_order_id_customer_list_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_list',
            name='daily_order_id',
        ),
        migrations.RemoveField(
            model_name='customer_list',
            name='order_id',
        ),
    ]
