# Generated by Django 5.0.4 on 2024-05-04 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shriharidoodhapp', '0004_remove_customer_list_daily_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delievery_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('delievery_status', models.IntegerField(default=0)),
                ('Delivery_Boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('daily_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shriharidoodhapp.package')),
                ('orderid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shriharidoodhapp.orders')),
            ],
        ),
    ]
