# Generated by Django 5.0.4 on 2024-05-05 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shriharidoodhapp', '0005_delievery_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delievery_management',
            name='daily_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shriharidoodhapp.package'),
        ),
    ]
