# Generated by Django 5.0.4 on 2024-05-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shriharidoodhapp', '0006_alter_delievery_management_daily_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='gap_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
