# Generated by Django 5.0.4 on 2024-05-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shriharidoodhapp', '0008_alter_delievery_management_daily_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delievery_management',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
