# Generated by Django 5.0.4 on 2024-05-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shriharidoodhapp', '0009_alter_delievery_management_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
